/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentVersioning from "@notum-cz/strapi-plugin-content-versioning/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import duplicateButton from "strapi-plugin-duplicate-button/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import githubActionTrigger from "../../src/plugins/github-action-trigger/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "content-versioning": contentVersioning,
    "color-picker": colorPicker,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "duplicate-button": duplicateButton,
    "import-export-entries": importExportEntries,
    "multi-select": multiSelect,
    "github-action-trigger": githubActionTrigger,
  },
});
